#!/bin/bash

set -e  # Exit on errors

input="$1"
ext="${input##*.}"
base=$(basename "$input")
tmpfile="tmp436536456.ff"

cleanup() {
    rm -f "$tmpfile"
}
trap cleanup EXIT

case "$ext" in
    ff) cp "$input" "$tmpfile" ;;
    ffz|lz) lzip -d -c "$input" > "$tmpfile" ;;
    ffbz|bz2) bzip2 -d -c "$input" > "$tmpfile" ;; #cannot view zipped 1fpirate
    ffzx|xz) xz -d -c "$input" > "$tmpfile" ;;
    png|jpg|gif) #2ff < "$input" > "$tmpfile" ;;
	sxiv "$input"
	exit 0 ;;
    1f|1ff|1fpirate)
	1fpirate "$input"
	exit 0 ;;
	#1ff2ff "$input" > "$tmpfile" ;;
    *)
        echo "Unsupported format: .$ext"
        exit 1
        ;;
esac

ffpirate "$tmpfile"
